### ISSUE TITLE
Error when i import

### ISSUE THREAD

**Issue by harshu4** [Cocos-BCX/cocos-bcx-node-bin#45]
unlocked >>> import_key chand 5Joz93MgW7xZH9PAP32CfNDPo41Z7ECLUBvoF9pMfubDQ7cSKQ1
10 assert_exception: Assert Exception
rec && rec->name == account_name_or_id: 
    {}
    th_a  wallet.cpp:677 get_account

**Comment by harshu4** [comment]
okhay they were ongoing an update , that made this happened i am closing this as now they have updated and everything works fine

**Comment by sara11-web** [comment]
Good
